apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-deployment
  namespace: python-web-app
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  strategy:
    tyoe: Recreate
  template:
    metadata:
      name: postgresql
      labels:
        app: postgresql
    spec:
      containers:
        - name: python-pg-db
          image: nitesh2611/python-pg-db:latest
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgsql-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: pgsql-config
                key: POSTGRES_DB
          volumeMounts:
            - name: pgsql-data
              mountPath: /var/lib/pgsql
      volumes:
        - name: pgsql-data
          persistentVolumeClaim:
            claimName: pvc

---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
  namespace: python-web-app
spec:
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
