apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: python-web-app
  labels:
      app: postgres
spec:
  type: NodePort
  ports:
    - name: postgres-deployment
      protocol: TCP
      port: 5432  # PostgreSQL default port
      targetPort: 5432
  selector:
    app: postgres