# postgresql-persistent-volume-claim.yaml (Optional, if you're not using dynamic provisioning)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-0
  namespace: python-web-app # The naming convention will depend on your StatefulSet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Should match the volumeClaimTemplates in the StatefulSet