apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: python-web-app
  labels:
    app: postgres
spec:
  storageClassName: postgres-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "500Mi"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-log-pvc
  namespace: python-web-app
  labels:
    app: postgres
spec:
  storageClassName: postgres-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "250Mi"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-pvc
  namespace: python-web-app
  labels:
    app: postgres
spec:
  storageClassName: postgres-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "128Mi"