apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: python-web-app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  provisioner:
  storageClassName: ebs-sc
  hostPath:
    path: /root/data    
