apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: python-web-app  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc
          
