apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: python-web-app  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""    
  resources:
    requests:
      storage: 5Gi
  storageClassName: microk8s-hostpath
          
