apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-deployment
  namespace: {{.Values.namespace.name }}
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      name: postgresql
      labels:
        app: postgresql
    spec:
      containers:
        - name: python-pg-db
          image: {{ .Values.postgresql.repository }}:{{ .Values.postgresql.tag }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: {{ .Values.volumeMounts.name }}
              mountPath: {{ .Values.volumeMounts.mountPath }}
      volumes:
        - name: local-storage
          persistentVolumeClaim:
            claimName: pvc

---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
  namespace: {{.Values.namespace.name }}
spec:
  selector:
    app: postgresql
  ports:
    - port: {{ .Values.postgresService.port }}
      targetPort: {{ .Values.targetPort.port }}
      protocol: {{ .Values.targetPort.protocol }}
