apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: {{.Values.namespace.name }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain  
  hostPath:
    path: /root/data    
