apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""    
  resources:
    requests:
      storage: 5Gi
  storageClassName: default-storageclass
          
