# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop" ]
    paths-ignore:
      - "helm/**"
      - "README.md"
      - "k8s/**"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Trivy scanner without cache
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        cache: 'false'
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'  
  build-python-img-and-push:     
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4       
          # Add support for more platforms with QEMU (optional)
          # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  

      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      
      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME }}/python-web-app:${{github.run_id}}
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/nitesh2611/python-web-app:${{github.run_id}}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'     
  update-python-app-img-in-helm-chart:
      runs-on: ubuntu-latest
      needs: build-python-img-and-push
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.TOKEN }}
        - name: Update image tag in helm chart
          run: |
            sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/python-pg-chart/values.yaml
            cat helm/python-pg-chart/values.yaml
            echo "Updated image tag in helm chart"
        - name: Commit changes
          run: |
            git config --global user.email "niteshwayafalkar@gmail.com"
            git config --global user.name "Nitesh Wayafalkar"
            git add helm/python-pg-chart/values.yaml
            git commit -m "Update tag in Helm chart"
            git push   

  build-python-pg-db-and-push:     
    needs: [update-python-app-img-in-helm-chart]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4       
               # Add support for more platforms with QEMU (optional)
                # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  
   
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
            
      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
            context: .
            file: ./PG_Dockerfile
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME }}/python-pg-db:${{github.run_id}}
            
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
            image-ref: 'docker.io/nitesh2611/python-pg-db:${{github.run_id}}'
            format: 'table'
            exit-code: '0'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'                 
  update-pg-image-tag-in-helm-chart:
      runs-on: ubuntu-latest
      needs: build-python-pg-db-and-push
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.TOKEN }}
        - name: Update image tag in helm chart
          run: |
            sed -i 's/pg_tag: .*/pg_tag: "${{github.run_id}}"/' helm/python-pg-chart/values.yaml
            cat helm/python-pg-chart/values.yaml
            echo "Updated image tag in helm chart"
        - name: Commit changes
          run: |
            git config --global user.email "niteshwayafalkar@gmail.com"
            git config --global user.name "Nitesh Wayafalkar"
            git add helm/python-pg-chart/values.yaml
            git commit -m "Update tag in Helm chart"
            git push   
      
